apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-k8s
  template:
    metadata:
      labels:
        app: nodejs-k8s
    spec:
      containers:
      - name: nodejs-k8s
        image: 411307820369.dkr.ecr.us-east-1.amazonaws.com/nodejs-k8s:latest
        ports:
        - containerPort: 3000
